// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAALYs2IDx6m6VSttcjAwFC87aTfp7ONM4',
    appId: '1:897571099842:web:604714699ffd7f5ce0175b',
    messagingSenderId: '897571099842',
    projectId: 'screen2green-tuankietbuv',
    authDomain: 'screen2green-tuankietbuv.firebaseapp.com',
    storageBucket: 'screen2green-tuankietbuv.firebasestorage.app',
    measurementId: 'G-V4943K1FK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG9corDyCQsIeFjL0T7-JDHJ3VVX_BPpg',
    appId: '1:897571099842:android:81790afe26297ec5e0175b',
    messagingSenderId: '897571099842',
    projectId: 'screen2green-tuankietbuv',
    storageBucket: 'screen2green-tuankietbuv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaHB4MsjCMTuVUwyBgjr-lNtGpIlOJzHo',
    appId: '1:897571099842:ios:5b70b96d2b4a6f7ae0175b',
    messagingSenderId: '897571099842',
    projectId: 'screen2green-tuankietbuv',
    storageBucket: 'screen2green-tuankietbuv.firebasestorage.app',
    androidClientId: '897571099842-d66gbio3ug229cdi2efapi6q4ml74h51.apps.googleusercontent.com',
    iosClientId: '897571099842-qivc37r4ho8llubrsfpipr2fu84ti378.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaHB4MsjCMTuVUwyBgjr-lNtGpIlOJzHo',
    appId: '1:897571099842:ios:5b70b96d2b4a6f7ae0175b',
    messagingSenderId: '897571099842',
    projectId: 'screen2green-tuankietbuv',
    storageBucket: 'screen2green-tuankietbuv.firebasestorage.app',
    androidClientId: '897571099842-d66gbio3ug229cdi2efapi6q4ml74h51.apps.googleusercontent.com',
    iosClientId: '897571099842-qivc37r4ho8llubrsfpipr2fu84ti378.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAALYs2IDx6m6VSttcjAwFC87aTfp7ONM4',
    appId: '1:897571099842:web:604714699ffd7f5ce0175b',
    messagingSenderId: '897571099842',
    projectId: 'screen2green-tuankietbuv',
    authDomain: 'screen2green-tuankietbuv.firebaseapp.com',
    storageBucket: 'screen2green-tuankietbuv.firebasestorage.app',
    measurementId: 'G-V4943K1FK9',
  );

}